# ==============================================================================
# Supabase 設定檔 (語法修正版)
# ==============================================================================

# 專案 ID，用於連結遠端 Supabase 專案
project_id = "zeezdsypknngfcodgjkd"

[api]
port = 54321
schemas = ["public", "storage", "graphql"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

# 【核心修正】
# 將 import_map 設定移到檔案的頂層。
# 這會告訴 Supabase CLI 在處理所有 functions 時，
# 都使用這個指定的 import map 檔案。
# 它不再屬於 [functions] 區塊。
import_map = "supabase/import_map.json"

# [functions] 區塊可以保留，用於定義函式相關的設定，
# 但 import_map 不在這裡。
[functions]
  # 例如，您可以在這裡為特定函式設定 JWT 驗證
  # [functions.my-function]
  #   verify_jwt = true