# ==============================================================================
# 檔案路徑: supabase/config.toml
# 版本: v42.1 - TOML 语法紧急修正
# ------------------------------------------------------------------------------
# 【此為完整檔案，可直接覆蓋】
# ==============================================================================

# [INFO] 專案 ID
project_id = "zeezdsypknngfcodgjkd"

# [INFO] 本地 API 伺服器設定
[api]
port = 54321
schemas = ["public", "storage", "graphql"]
max_rows = 1000

# [INFO] 本地資料庫設定
[db]
port = 54322
major_version = 15

# [INFO] 本地 Supabase Studio 設定
[studio]
port = 54323

# [v42.1 核心修正] Edge Functions 的精细化部署设定 (纵深防御)
# ------------------------------------------------------------------------------
# [架構原則] 信任的最小化 (Zero Trust Principle)
# 此區塊採用「白名單」模式。只有在此處被明確設定為 verify_jwt = false 的
# 函式，才會對匿名使用者開放。所有未在此列出的函式，都將採用 Supabase
# 的預設安全行為 (verify_jwt = true)，即強制要求提供有效的 JWT。
# 這確保了我們的系統在閘道層就具備了第一道防線。
# ------------------------------------------------------------------------------
[functions]
  # 函式 1: 訂單建立中樞
  # 理由: 必須處理已登入、未登入會員、純訪客三種情境的結帳請求。
  [functions.create-order-from-cart]
    verify_jwt = false

  # 函式 2: 購物車管理與計算
  # 理由: 必須處理匿名及已登入使用者的購物車增、刪、改、查操作。
  [functions.recalculate-cart]
    verify_jwt = false

  # 函式 3: 購物車獲取/建立
  # 理由: 這是匿名使用者購物流程的起點，必須允許匿名請求來建立一個
  #       與其綁定的購物車。
  [functions.get-or-create-cart]
    verify_jwt = false

  # [v42.0 新增] 後台 Supabase Client 安全金鑰獲取
  # 理由: 這是後台應用程式初始化時，安全獲取 anon key 的端點，
  #       此階段使用者尚未登入，因此不能驗證 JWT。
  [functions.config]
    verify_jwt = false