# 檔案路徑: supabase/config.toml
# 版本: v43.2 (基於 v42.2 的增量追加修正版)
# 說明: 此版本嚴格基於 v42.2 原始檔案，在不異動任何既有設定的前提下，
#       僅「追加」新函式所需的匿名存取權限，並完成正體中文校訂。

# [INFO] 專案 ID
project_id = "zeezdsypknngfcodgjkd"

# [INFO] 本地 API 伺服器設定
[api]
port = 54321
schemas = ["public", "storage", "graphql"]
max_rows = 1000

# [INFO] 本地資料庫設定
[db]
port = 54322
major_version = 15

# [INFO] 本地 Supabase Studio 設定
[studio]
port = 54323

# [v42.1 核心修正] Edge Functions 的精細化部署設定 (縱深防禦)
# ------------------------------------------------------------------------------
# [架構原則] 信任的最小化 (Zero Trust Principle)
# 此區塊採用「白名單」模式。只有在此處被明確設定為 verify_jwt = false 的
# 函式，才會對匿名使用者開放。所有未在此列出的函式，都將採用 Supabase
# 的預設安全行為 (verify_jwt = true)，即強制要求提供有效的 JWT。
# 這確保了我們的系統在閘道層就具備了第一道防線。
# ------------------------------------------------------------------------------
[functions]
  # 函式 1: 訂單建立中樞
  # 理由: 必須處理已登入、未登入會員、純訪客三種情境的結帳請求。
  [functions.create-order-from-cart]
    verify_jwt = false

  # +++ [v42.2 新增原子化函式] +++
  # 函式 2: 原子化購物車管理 (重構後為 CQRS 命令函式)
  # 理由: 必須處理匿名及已登入使用者的所有購物車修改操作，取代舊的 recalculate-cart。
  [functions.manage-cart]
    verify_jwt = false
  # +++++++++++++++++++++++++++++

  # 函式 3: 購物車獲取/建立
  # 理由: 這是匿名使用者購物流程的起點，必須允許匿名請求來建立一個
  #       與其綁定的購物車。
  [functions.get-or-create-cart]
    verify_jwt = false

  # [v42.0 新增] 後台 Supabase Client 安全金鑰獲取
  # 理由: 這是後台應用程式初始化時，安全獲取 anon key 的端點，
  #       此階段使用者尚未登入，因此不能驗證 JWT。
  [functions.config]
    verify_jwt = false

# --- [v43.2 增量追加] 為新的 CQRS 與日誌函式補上權限配置 ---
  # 函式 5: CQRS - 查詢函式 (讀取)
  # 理由: 必須允許匿名及已登入使用者讀取其購物車的最新狀態。
  [functions.get-cart-snapshot]
    verify_jwt = false
    
  # 函式 6: 前端日誌回傳
  # 理由: 必須允許任何前端（無論登入與否）上報錯誤日誌。
  [functions.log-client-error]
    verify_jwt = false
# -------------------------------------------------------------