==============================================================================
檔案路徑: supabase/config.toml
------------------------------------------------------------------------------
檔案名稱：config.toml
檔案職責：Supabase 專案的主設定檔，定義本地開發環境與 Edge Functions 的部署行為。
版本：1.2 (TOML 語法修正版)
SOP 條款對應：
- [SOP v7.2, 2.1.4.2] 語法適應性規範
- [SOP v7.2, 0.8.2(e)] 語法健全性掃描
AI 註記：
變更摘要:
- [標頭]::[核心修正]::將所有註解從不相容的 // 與 /** 格式，
修正為 TOML 標準的 # 格式，以解決部署時的解析錯誤。
- [functions]::[保留]::完整保留 v1.1 版本中對 manage-cart 函式的正確部署設定。
更新日誌 (Changelog)：
- v1.2 (2025-09-17)：修正 TOML 註解語法，解決部署失敗問題。
- v1.1 (2025-09-17)：同步程式碼架構，移除舊函式引用，新增新函式引用。
==============================================================================
[INFO] 專案 ID
project_id = "zeezdsypknngfcodgjkd"
[INFO] 本地 API 伺服器設定
[api]
port = 54321
schemas = ["public", "storage", "graphql"]
max_rows = 1000
[INFO] 本地資料庫設定
[db]
port = 54322
major_version = 15
[INFO] 本地 Supabase Studio 設定
[studio]
port = 54323
Edge Functions 的精细化部署设定 (纵深防御)
------------------------------------------------------------------------------
[架構原則] 信任的最小化 (Zero Trust Principle)
此區塊採用「白名單」模式。只有在此處被明確設定為 verify_jwt = false 的
函式，才會對匿名使用者開放。所有未在此列出的函式，都將採用 Supabase
的預設安全行為 (verify_jwt = true)，即強制要求提供有效的 JWT。
------------------------------------------------------------------------------
[functions]
函式 1: 訂單建立中樞
理由: 必須處理已登入、未登入會員、純訪客三種情境的結帳請求。
[functions.create-order-from-cart]
verify_jwt = false
函式 2: 原子化購物車管理
理由: 必須處理匿名及已登入使用者的所有購物車操作。
[functions.manage-cart]
verify_jwt = false
函式 3: 購物車獲取/建立
理由: 這是匿名使用者購物流程的起點，必須允許匿名請求來建立一個
與其綁定的購物車。
[functions.get-or-create-cart]
verify_jwt = false
函式 4: 後台 Supabase Client 安全金鑰獲取
理由: 這是前端應用程式初始化時，安全獲取 anon key 的端點。
[functions.config]
verify_jwt = false